const INSTANCE_BIND_TYPE = {
  CLASS: 0,
  FUNCTION: 1,
  INSTANCE: 2
};

const INSTANCE_NAME_PREFIX = '$$';
const INSTANCE_INJECTOR_NAME = 'injector';
module.exports = {
  INSTANCE_BIND_TYPE,
  INSTANCE_NAME_PREFIX,
  INSTANCE_INJECTOR_NAME
};